name: CI Staging deploy

on:
  push:
    branches:
      - development
jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v3

      - name: Build 🏗️
        uses: ./.github/actions/build
        env:
          VITE_BASHAWAY_BE_URL: ${{ secrets.STAGING_BASHAWAY_BE_URL }}
          VITE_APP_ENV: staging

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
